In [1]:
%matplotlib widget
import numpy as np
import matplotlib.pyplot as plt
import xarray as xr

import gsw

from scipy.integrate import solve_ivp

from scipy.interpolate import interp1d

In [2]:
ds = xr.open_dataset('data/MBARI_StationM_ADCP_201711_201811.nc')

In [3]:
lat = 35+8.4585/60
bini = 15

Smooth ADCP time series
* 30-min running median to remove spikes
* 60-min running mean to smooth

In [4]:
ds['binheight'][bini]

<xarray.DataArray 'binheight' ()>
array(17.14)

In [5]:
ds['Eas_sm'] = ds['Eas'].rolling(time=6,center=True).median().rolling(time=12,center=True).mean()
ds['Nor_sm'] = ds['Nor'].rolling(time=6,center=True).median().rolling(time=12,center=True).mean()

In [6]:
plt.figure(figsize=(8,4))
plt.plot(ds['time'],ds['Eas_sm'][:,bini]);
plt.plot(ds['time'],ds['Eas'][:,bini],'--');
plt.plot(ds['time'],ds['Eas_sm'][:,1],'-');
#plt.plot(ds['time'],ds['Eas'][:,1]);
plt.ylabel('m/s')
plt.title('eastward velocity')

FigureCanvasNbAgg()

Text(0.5, 1.0, 'eastward velocity')

In [7]:
plt.figure(figsize=(8,4))
plt.plot(ds['time'],ds['Nor_sm'][:,bini]);
plt.legend(['Bin 15','Bin 1'])
plt.ylabel('m/s')
plt.title('northward velocity')

FigureCanvasNbAgg()

Text(0.5, 1.0, 'northward velocity')

### Test with limited obs


In [8]:
zf = ds['binheight'][bini] # upper boundary height
zobs = np.array(ds['binheight'][0:(bini+1)])

In [9]:
i = 1j
kappa = 0.41 # Von Karman constant
f = gsw.f(lat)

In [10]:
gi = np.isfinite(ds['Eas_sm'][:,0])
tobs = np.array((ds['time'][gi] - ds['time'][gi][0])/np.timedelta64(1,'s')) # array of times in seconds
deltat = tobs[1]-tobs[0]

In [11]:
wobs = np.array(ds['Eas_sm'][gi,0:(bini+1)]+i*ds['Nor_sm'][gi,0:(bini+1)])
dwobsdt = np.gradient(wobs,deltat,axis=0)

In [12]:
np.where(gi)

(array([    9,    10,    11, ..., 98198, 98199, 98200]),)

In [13]:
ds['time'][gi]

<xarray.DataArray 'time' (time: 98192)>
array(['2017-11-10T10:48:13.760000000', '2017-11-10T10:53:13.760000000',
       '2017-11-10T10:58:13.760000000', ..., '2018-10-17T09:13:13.720000000',
       '2018-10-17T09:18:13.720000000', '2018-10-17T09:23:13.720000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2017-11-10T10:48:13.760000 ... 2018-10-17T09:23:13.720000

In [14]:
ds['time'][9]

<xarray.DataArray 'time' ()>
array('2017-11-10T10:48:13.760000000', dtype='datetime64[ns]')
Coordinates:
    time     datetime64[ns] 2017-11-10T10:48:13.760000

In [15]:
def dwdt_bbl(t, w_in):
    # Note that w_in is real and complex parts concatenates
    # need to combine into complex numbers
    # Scipy docs say that ode solvers RK45 and BDF can be used in complex plane
    # https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.BDF.html#scipy.integrate.BDF
    # but perhaps this does not work for *arrays* of complex numbers?
    
    global zo
    
    N = int(len(w_in)/2)
    w = w_in[:N]+i*w_in[N:]
    
    winf = np.interp(t,tobs,wobs[:,bini])
    dwinfdt = np.interp(t,tobs,dwobsdt[:,bini])

    F = dwinfdt + i*f*winf
    ustar = kappa*zo*np.abs(w[0])/dz[0]
    coef1 = 2*kappa*ustar/(dz[:-1]+dz[1:])

    wall = np.concatenate([np.atleast_1d(0+i*0),w,np.atleast_1d(winf)])
    
    dwalldt = np.nan*np.ones(np.shape(wall))+i*np.nan*np.ones(np.shape(wall))
    dwalldt[1:-1] = (F +
                     coef1*(z[1:-1]/dz[1:])*wall[2:] +
                     (-i*f - coef1*(z[1:-1]/dz[1:]+z[:-2]/dz[:-1]))*wall[1:-1] +
                     coef1*(z[:-2]/dz[:-1])*wall[:-2])
    
    dwdt = dwalldt[1:-1]
    
    dwdt_out = np.concatenate([np.real(dwdt),np.imag(dwdt)])
    
    return dwdt_out

In [16]:
nzo = 7
zo_array = np.logspace(-4,-1,nzo) # roughness length array

tf = 31*86400
ntimes = len(tobs[tobs<=tf])

nz = 201

w_sol_all = np.nan*np.ones([ntimes,nz-2,nzo]) + i*np.nan*np.ones([ntimes,nz-2,nzo])
w_sol_obs_all = np.nan*np.ones([ntimes,len(zobs),nzo]) + i*np.nan*np.ones([ntimes,len(zobs),nzo])

for zi,zo in enumerate(zo_array):
    print('zo:',zo,'(',zi+1,'/',nzo,')')

    z = np.logspace(np.log10(zo),np.log10(zf),nz)
    dz = np.diff(z)
    
    w0_obs = np.interp(z,zobs[1:bini],wobs[0,1:bini])[1:-1]
    w0 = np.concatenate([np.real(w0_obs),
                           np.imag(w0_obs)])

    tic = np.datetime64('now')
    a = solve_ivp(dwdt_bbl, t_span=[tobs[0],tf], y0 = w0, t_eval = tobs[tobs<=tf], method='BDF')
    toc = np.datetime64('now')
    print(toc-tic)
    
    N = int(np.shape(a.y)[0]/2)
    t_sol = a.t
    w_sol = a.y[:N,:]+i*a.y[N:,:]
    
    fint= interp1d(z[1:-1],w_sol,axis=0,
                   bounds_error=False,fill_value = np.nan+i*np.nan)
    w_sol_obs = fint(zobs)
    
    w_sol_all[:,:,zi] = w_sol.T
    w_sol_obs_all[:,:,zi] = w_sol_obs.T

zo: 0.0001 ( 1 / 7 )
662 seconds
zo: 0.00031622776601683794 ( 2 / 7 )
643 seconds
zo: 0.001 ( 3 / 7 )
444 seconds
zo: 0.0031622776601683794 ( 4 / 7 )
488 seconds
zo: 0.01 ( 5 / 7 )
499 seconds
zo: 0.03162277660168379 ( 6 / 7 )
530 seconds
zo: 0.1 ( 7 / 7 )
610 seconds


In [17]:
bbl_sols = xr.Dataset(
        data_vars={'uobs_subset':    (('tobs', 'zobs'), np.real(wobs[tobs<=tf,:])),
                   'vobs_subset':    (('tobs', 'zobs'), np.imag(wobs[tobs<=tf,:])),
                   'usol_all': (('tobs','zsol','zo'), np.real(w_sol_all)),
                   'vsol_all': (('tobs','zsol','zo'), np.imag(w_sol_all)),
                   'usol_obs_all': (('tobs','zobs','zo'), np.real(w_sol_obs_all)),
                   'vsol_obs_all': (('tobs','zobs','zo'), np.imag(w_sol_obs_all)),                  },
        coords={'zobs': zobs,
                'tobs': tobs[tobs<=tf],
                'zo':zo_array})
bbl_sols.to_netcdf('bbl_sols_neww.nc',mode='w')
bbl_sols.close()

In [18]:
w_sol = np.squeeze(w_sol_all[:,:,0])

In [19]:
plt.figure()
plt.subplot(211)
plt.plot(t_sol,np.real(w_sol),color='gray')
plt.plot(tobs[0:12],np.real(wobs[0:12,bini]))

plt.subplot(212)
plt.plot(t_sol,np.imag(w_sol),color='gray')
plt.plot(tobs[0:12],np.imag(wobs[0:12,bini]))

FigureCanvasNbAgg()

In [20]:
plt.figure()
plt.plot(np.imag(np.squeeze(w_sol_obs_all[-1,:,:])),zobs)

FigureCanvasNbAgg()

In [21]:
np.diff(a.t[0:100])

array([300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.])

### Test with steady forcing

In [22]:
winf_steady = 0.04+i*0
w0_steady = np.concatenate([np.real(winf_steady)*np.ones(N),
                           np.imag(winf_steady)*np.ones(N)])
zo = 0.01

def dwdt_bbl_steady(t, w_in):
    N = int(len(w_in)/2)
    w = w_in[:N]+i*w_in[N:]
    
    winf = winf_steady
    dwinfdt = 0+i*0

    F = dwinfdt + i*f*winf
    ustar = kappa*zo*np.abs(w[1])/dz[0]
    coef1 = 2*kappa*ustar/(dz[:-1]+dz[1:])

    wall = np.concatenate([np.atleast_1d(0+i*0),w,np.atleast_1d(winf)])
    
    dwalldt = np.nan*np.ones(np.shape(wall))+i*np.nan*np.ones(np.shape(wall))
    dwalldt[1:-1] = (F +
                     coef1*(z[1:-1]/dz[1:])*wall[2:] +
                     (-i*f - coef1*(z[1:-1]/dz[1:]+z[:-2]/dz[:-1]))*wall[1:-1] +
                     coef1*(z[:-2]/dz[:-1])*wall[:-2])
    
    dwdt = dwalldt[1:-1]
    #print(dwdt)
    
    dwdt_out = np.concatenate([np.real(dwdt),np.imag(dwdt)])
    
    return dwdt_out

In [24]:
modsteady = solve_ivp(dwdt_bbl_steady, t_span=[0,2*86400], 
                      y0 = w0_steady, method='BDF')

In [25]:
t_sol_steady = modsteady.t
w_sol_steady = modsteady.y[:N,:]+i*modsteady.y[N:,:]

In [26]:
plt.figure()
plt.subplot(121)
plt.plot(np.real(w_sol_steady[:,-1]),z[1:-1]);
plt.plot(np.imag(w_sol_steady[:,-1]),z[1:-1]);
#plt.plot(tobs[0:12*24],wobs[0:12*24,bini])

FigureCanvasNbAgg()

In [27]:
ustar_steady = kappa*zo*np.abs(w_sol_steady[1,-1])/dz[0]

In [28]:
ustar_steady

0.0010053975739126623

In [29]:
dz

array([0.00260536, 0.00267324, 0.00274289, 0.00281435, 0.00288767,
       0.00296291, 0.0030401 , 0.00311931, 0.00320058, 0.00328396,
       0.00336952, 0.00345731, 0.00354739, 0.00363981, 0.00373464,
       0.00383194, 0.00393178, 0.00403421, 0.00413932, 0.00424716,
       0.00435782, 0.00447135, 0.00458785, 0.00470738, 0.00483002,
       0.00495586, 0.00508498, 0.00521746, 0.0053534 , 0.00549287,
       0.00563598, 0.00578282, 0.00593348, 0.00608807, 0.00624669,
       0.00640944, 0.00657643, 0.00674777, 0.00692357, 0.00710395,
       0.00728904, 0.00747894, 0.0076738 , 0.00787373, 0.00807886,
       0.00828935, 0.00850532, 0.00872691, 0.00895428, 0.00918757,
       0.00942694, 0.00967254, 0.00992455, 0.01018312, 0.01044843,
       0.01072065, 0.01099996, 0.01128655, 0.0115806 , 0.01188232,
       0.01219189, 0.01250954, 0.01283546, 0.01316987, 0.01351299,
       0.01386505, 0.01422629, 0.01459693, 0.01497723, 0.01536745,
       0.01576782, 0.01617863, 0.01660014, 0.01703264, 0.01747